In [ ]:
# Basic If-Else Statements:

In [1]:
# 1. Write a Python program to check if a given number is positive or negative.

num = float(input("Enter a number: "))
if num > 0:
print("Positive number")
elif num == 0:
print("Zero")
else:
print("Negative number")

Enter a number:  5


Positive number


In [2]:
# 2. Create a program that determines if a person is eligible to vote based on their age.

age = int(input("Enter you age: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter you age:  25


You are eligible to vote


In [3]:
# 3. Develop a program to find the maximum of two numbers using if-else statements.

a = 12514
b = 12571
def maximum(a, b):    
    if a >= b:
        return a
    else:
        return b
print(maximum(a, b))

12571


In [4]:
# 4. Write a Python script to classify a given year as a leap year or not.

year = int(input("Enter a year: "))
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
else:
    print("{0} is not a leap year".format(year))

Enter a year:  2020


2020 is a leap year


In [7]:
# 5. Create a program that checks whether a character is a vowel or a consonant.

x = input("Enter character:") 
if (x == 'a' or x == 'e' or x == 'i' or x == 'o' or x == 'u'): 
    print("Vowel") 
else: 
     print("Consonant") 

Enter character: b


Consonant


In [8]:
# 6. Implement a program to determine whether a given number is even or odd.

num = int(input("Enter a number: "))
if (num % 2) == 0:
    print("{0} is Even".format(num))
else:
    print("{0} is Odd".format(num))

Enter a number:  25


25 is Odd


In [10]:
# 7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

def my_abs(value):
    if value <= 0:
        return value * -1
    return value * 1
print(my_abs(-3.5))
print(my_abs(3.5))

3.5
3.5


In [11]:
# 8. Develop a program that determines the largest of three given numbers using if-else statements.

num1 = 10
num2 = 14
num3 = 12

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3
print("The largest number is", largest)

The largest number is 14


In [13]:
# 9. Create a program that checks if a given string is a palindrome.

def isPalindrome(s):
    return s == s[::-1]
s = "pop"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

Yes


In [16]:
# 10. Write a Python program to calculate the grade based on a student's score.

score = int(input("Enter your marks"))

if score>=90:
    print("excellent performance your grade is A+")
elif score>=80:
    print("Good performance your grade is A")
elif score>=70:
     print("Average performance your grade is B")
else:
     print("Poor performance your grade is C")

Enter your marks 58


Poor performance your grade is C


In [ ]:
# Nested If-Else Statements:

In [17]:
# 11. Write a program to find the largest among three numbers using nested if-else statements.

a=int(input("Enter A: "))
b=int(input("Enter B: "))
c=int(input("Enter C: "))
if a>b:
    if a>c:
        g=a
    else:
        g=c
else:
    if b>c:
        g=b
    else:
        g=c

print("Greater  = ",g)

Enter A:  871
Enter B:  652
Enter C:  879


Greater  =  879


In [22]:
# 12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  45
y:  75
z:  60


Scalene triangle


In [39]:
# 13. Develop a program that checks if a year is a leap year and also if it is a century year.

year = int(input("Enter a year: "))
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year and century year".format(year))
elif (year % 4 ==0) and (year % 100 == 0):
    print("{0} is a leap year and century year".format(year))
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year and not century year".format(year))
elif (year % 4 !=0) and (year % 100 == 0):
    print("{0} is not a leap year but century year".format(year))
else:
    print("{0} is not a leap year and also not century year".format(year))

Enter a year:  2300


2300 is a leap year and century year


In [40]:
# 14. Write a Python script to determine if a number is positive, negative, or zero.

num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number:  -24


Negative number


In [42]:
# 15. Create a program to check if a person is a teenager (between 13 and 19 years old).

age = int(input("Enter you age: "))

if age >= 13 and age <= 19:
    print("Teenager")
else:
    print("Not Teenager")

Enter you age:  15


Teenager


In [44]:
# 16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

A = int(input("enter the number of 1 : "))
B = int(input("enter the number of 2 : "))
C = int(input("enter the number of 3 : "))

if A+B+C != 180 or A<0 or A>180 or B<0 or B>180 or C<0 or C>180:
    print("NOT TRIANGLE")

elif A<90 and B<90 and C<90:
    print("acute angle")

elif (A>90 and A<180) or (B>90 and B<180) or (C>90 and C<180):
    print("obtuse angle")

elif A==90 or B==90 or C==90:
    print("carpenter's triangle")

else:
    print("Wut?")

enter the number of 1 :  45
enter the number of 2 :  65
enter the number of 3 :  70


acute angle


In [45]:
# 17. Write a Python program to calculate the roots of a quadratic equation.

import math

a = int(input("Please Enter a Value of a Quadratic Equation : "))
b = int(input("Please Enter b Value of a Quadratic Equation : "))
c = int(input("Please Enter c Value of a Quadratic Equation : "))

discriminant = (b * b) - (4 * a * c)

if(discriminant > 0):
    root1 = (-b + math.sqrt(discriminant) / (2 * a))
    root2 = (-b - math.sqrt(discriminant) / (2 * a))
    print("Two Distinct Real Roots Exists: root1 = %.2f and root2 = %.2f" %(root1, root2))
elif(discriminant == 0):
    root1 = root2 = -b / (2 * a)
    print("Two Equal and Real Roots Exists: root1 = %.2f and root2 = %.2f" %(root1, root2))
elif(discriminant < 0):
    root1 = root2 = -b / (2 * a)
    imaginary = math.sqrt(-discriminant) / (2 * a)
    print("Two Distinct Complex Roots Exists: root1 = %.2f+%.2f and root2 = %.2f-%.2f" %(root1, imaginary, root2, imaginary))

Please Enter a Value of a Quadratic Equation :  4
Please Enter b Value of a Quadratic Equation :  6
Please Enter c Value of a Quadratic Equation :  7


Two Distinct Complex Roots Exists: root1 = -0.75+1.09 and root2 = -0.75-1.09


In [48]:
# 18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2
# for Tuesday, etc.).

weekday = int(input("Enter weekday day number (1-7) : "))
if weekday == 1 :
    print("\nMonday");
elif weekday == 2 :
    print("\nTuesday")
elif(weekday == 3) :
    print("\nWednesday")
elif(weekday == 4) :
    print("\nThursday")
elif(weekday == 5) :
    print("\nFriday")
elif(weekday == 6) :
    print("\nSaturday")
elif (weekday == 7) :
    print("\nSunday")
else :
    print("\nPlease enter weekday number between 1-7.")

Enter weekday day number (1-7) :  5



Friday


In [50]:
# 19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

def is_leap(year):
    leap = False
    if (year % 4) == 0:
        if (year % 100) == 0:
            if (year % 400) == 0:
                leap = True
            else:
                leap = False
        else:
            leap = True
    else:
        leap = False
    
    return leap
is_leap(2017)

False

In [2]:
# 20. Develop a program that checks if a given number is prime or not using nested if-else statements.

num = 12
if num > 1:
    for i in range(2, int(num/2)+1):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

12 is not a prime number


In [ ]:
# Elif Statements:

In [3]:
# 21. Write a Python program to assign grades based on different ranges of scores using elif statements.

score = int(input("Enter your marks"))

if score>=90:
    print("excellent performance your grade is A+")
elif score>=80:
    print("Good performance your grade is A")
elif score>=70:
     print("Average performance your grade is B")
else:
     print("Poor performance your grade is C")

Enter your marks 95


excellent performance your grade is A+


In [1]:
# 22. Implement a program to determine the type of a triangle based on its angles.

print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  60
y:  60
z:  60


Equilateral triangle


In [5]:
# 23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using
# elif statements.

weight=float(input("Enter weight in Kg:"))
height=float(input("Enter height in cm:"))

bmi= weight/(height)**2

if bmi<18.5:
    print("Underweight")
elif bmi>=18.5 and bmi<25:
    print("Normal")
elif bmi>=25 and bmi<30:
    print("Overweight")
else:
    print("Obesity")

Enter weight in Kg: 56
Enter height in cm: 155


Underweight


In [6]:
# 24. Create a program that determines whether a given number is positive, negative, or zero using elif
# statements.

num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number:  51


Positive number


In [7]:
# 25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif
# statements.

ch = input("Please Enter Your Own Character : ")

if(ch.isupper()):
    print("The Given Character ", ch, "is an Uppercase Alphabet")
elif(ch.islower()):
    print("The Given Character ", ch, "is a Lowercase Alphabet")
else:
    print("The Given Character ", ch, "is a special character")

Please Enter Your Own Character :  @#$


The Given Character  @#$ is a special character


In [21]:
# 26. Implement a program to calculate the discounted price based on different purchase amounts using elif
# statements.

p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-5000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-5000)*(30/100.0)
else:
    dis=(p-5000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  25000


Discount Amount = 6000.00
Net Bill Amount = 19000.00


In [5]:
# 27. Develop a program to calculate the electricity bill based on different consumption slabs using elif
# statements.

def calculateBill(units): 
    if (units <= 100):     
        return units * 10;    
    elif (units <= 200):
        return ((100 * 10) + (units - 100) * 15);    
    elif (units <= 300): 
        return ((100 * 10) + (100 * 15) + (units - 200) * 20);     
    elif (units > 300): 
        return ((100 * 10) +
                (100 * 15) +
                (100 * 20) +
                (units - 300) * 25);      
    return 0; 
units =310
print(calculateBill(units)) 

4750


In [19]:
# 28. Create a program to determine the type of quadrilateral based on its angles and sides using elif
# statements.

print("Input lengths of the quadrilateral sides: ")
w = int(input("w: "))
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

print("Input angles of the quadrilateral: ")
a = int(input("a: "))
b = int(input("b: "))
c = int(input("c: "))
d = int(input("d: "))

if w == x == y == z and a == b == c == d:
	print("Given quadrilateral is Square")
elif w == x == y == z and a == c and b == d:
	print("Given quadrilateral is Rhombus")
elif w == y and x == z and a == b == c == d:
	print("Given quadrilateral is Rectangle")
else:
	print("Given quadrilateral is Trapezoid")

Input lengths of the quadrilateral sides: 


w:  45
x:  45
y:  45
z:  45


Input angles of the quadrilateral: 


a:  60
b:  120
c:  60
d:  120


Given quadrilateral is Rhombus


In [ ]:
print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

In [7]:
# 29. Write a Python script to determine the season based on a user-provided month using elif statements.

month = input("Input the month (e.g. January, February etc.): ")
day = int(input("Input the day: "))

if month in ('January', 'February', 'March'):
	season = 'winter'
elif month in ('April', 'May', 'June'):
	season = 'spring'
elif month in ('July', 'August', 'September'):
	season = 'summer'
else:
	season = 'autumn'

if (month == 'March') and (day > 19):
	season = 'spring'
elif (month == 'June') and (day > 20):
	season = 'summer'
elif (month == 'September') and (day > 21):
	season = 'autumn'
elif (month == 'December') and (day > 20):
	season = 'winter'

print("Season is",season)

Input the month (e.g. January, February etc.):  March
Input the day:  25


Season is spring


In [14]:
# 30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
# elif statements.

def leap_year(year):
    if year % 400 == 0:
        return True
    elif year % 100 == 0:
        return False
    elif year % 4 == 0:
        return True
    else:
        return False

def days_in_month(month):
    if month == 1 or month == 3 or month == 5 or month == 7 \
    or month == 8 or month == 10 or month == 12:
        return month == 31
    elif month == 2:
        if leap_year(year):
            return 29
        else:
            return 28
    else:
        return 30
year = 2019
month = 2
print(year, "leap year:", leap_year(year))
print("number of days in month", month, "is:", days_in_month(month))

2019 leap year: False
number of days in month 2 is: 28


In [ ]:
# Basic Level:

In [1]:
# 1. Write a Python program that checks if a given number is positive, negative, or zero.

num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number:  -12


Negative number


In [2]:
# 2. Create a program to determine if a person is eligible to vote based on their age.

age = int(input("Enter you age: "))

if age >= 18:
    print("You are eligible to vote")
else:
    print("You are not eligible to vote")

Enter you age:  18


You are eligible to vote


In [3]:
# 3. Write a program to find the maximum of two given numbers using conditional statements.

a = 115
b = 12
def maximum(a, b):    
    if a >= b:
        return a
    else:
        return b
print(maximum(a, b))

115


In [5]:
# 4. Develop a program that calculates the grade of a student based on their exam score.

score = int(input("Enter your marks"))

if score>=90:
    print("excellent performance your grade is A+")
elif score>=80:
    print("Good performance your grade is A")
elif score>=70:
     print("Average performance your grade is B")
else:
     print("Poor performance your grade is C")

Enter your marks 81


Good performance your grade is A


In [6]:
# 5. Create a program that checks if a year is a leap year or not.

year = int(input("Enter a year: "))
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
else:
    print("{0} is not a leap year".format(year))

Enter a year:  2018


2018 is not a leap year


In [7]:
# 6. Write a program to classify a triangle based on its sides' lengths.

print("Input lengths of the triangle sides: ")
x = int(input("x: "))
y = int(input("y: "))
z = int(input("z: "))

if x == y == z:
	print("Equilateral triangle")
elif x==y or y==z or z==x:
	print("isosceles triangle")
else:
	print("Scalene triangle")

Input lengths of the triangle sides: 


x:  80
y:  80
z:  50


isosceles triangle


In [9]:
# 7. Build a program that determines the largest of three given numbers.

num1 = 19
num2 = 14
num3 = 11

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3
print("The largest number is", largest)

The largest number is 19


In [10]:
# 8. Develop a program that checks whether a character is a vowel or a consonant.

x = input("Enter character:") 
if (x == 'a' or x == 'e' or x == 'i' or x == 'o' or x == 'u'): 
    print("Vowel") 
else: 
     print("Consonant") 

Enter character: o


Vowel


In [11]:
# 9. Create a program to calculate the total cost of a shopping cart based on discounts.

p=int(input('Enter purchase amount '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-5000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-5000)*(30/100.0)
else:
    dis=(p-5000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount  25000


Discount Amount = 6000.00
Net Bill Amount = 19000.00


In [12]:
# 10. Write a program that checks if a given number is even or odd.

num = int(input("Enter a number: "))
if (num % 2) == 0:
    print("{0} is Even".format(num))
else:
    print("{0} is Odd".format(num))

Enter a number:  251


251 is Odd


In [ ]:
Intermediate Level:

In [13]:
# 11. Write a program that calculates the roots of a quadratic equation .

import math

a = int(input("Please Enter a Value of a Quadratic Equation : "))
b = int(input("Please Enter b Value of a Quadratic Equation : "))
c = int(input("Please Enter c Value of a Quadratic Equation : "))

discriminant = (b * b) - (4 * a * c)

if(discriminant > 0):
    root1 = (-b + math.sqrt(discriminant) / (2 * a))
    root2 = (-b - math.sqrt(discriminant) / (2 * a))
    print("Two Distinct Real Roots Exists: root1 = %.2f and root2 = %.2f" %(root1, root2))
elif(discriminant == 0):
    root1 = root2 = -b / (2 * a)
    print("Two Equal and Real Roots Exists: root1 = %.2f and root2 = %.2f" %(root1, root2))
elif(discriminant < 0):
    root1 = root2 = -b / (2 * a)
    imaginary = math.sqrt(-discriminant) / (2 * a)
    print("Two Distinct Complex Roots Exists: root1 = %.2f+%.2f and root2 = %.2f-%.2f" %(root1, imaginary, root2, imaginary))

Please Enter a Value of a Quadratic Equation :  25
Please Enter b Value of a Quadratic Equation :  18
Please Enter c Value of a Quadratic Equation :  41


Two Distinct Complex Roots Exists: root1 = -0.36+1.23 and root2 = -0.36-1.23


In [14]:
# 12. Create a program that determines the day of the week based on the day number (1-7).

weekday = int(input("Enter weekday day number (1-7) : "))
if weekday == 1 :
    print("\nMonday");
elif weekday == 2 :
    print("\nTuesday")
elif(weekday == 3) :
    print("\nWednesday")
elif(weekday == 4) :
    print("\nThursday")
elif(weekday == 5) :
    print("\nFriday")
elif(weekday == 6) :
    print("\nSaturday")
elif (weekday == 7) :
    print("\nSunday")
else :
    print("\nPlease enter weekday number between 1-7.")

Enter weekday day number (1-7) :  4



Thursday


In [18]:
# 13. Develop a program that calculates the factorial of a given number using recursion.

def recur_factorial(n):
    if n == 1:
        return n
    else:
        return n*recur_factorial(n-1)
num = 7

# check if the number is negative
if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    print("The factorial of", num, "is", recur_factorial(num))

The factorial of 7 is 5040


In [19]:
# 14. Write a program to find the largest among three numbers without using the `max()` function.

num1 = 27
num2 = 42
num3 = 57

if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3
print("The largest number is", largest)

The largest number is 57


In [20]:
# 15. Create a program that simulates a basic ATM transaction menu.

user = { 'pin' : 1234, 'balance' : 1000}

def widthdraw_cash():
    while True:
        amount = int(input("Enter the amount of money you want to widthdraw: "))
        if amount > user['balance']:
            print("You don't have sufficient balance to make this widthdrawal")
        else:
            user['balance'] = user['balance'] - amount
            print(f"{amount} Dollars successfully widthdrawn your remaining balance is {user['balance']} Dollars")
            print('')
            return False

def balance_enquiry():
    print(f"Total balance {user['balance']} Dollars")
    print('')


is_quit = False

print('')
print("Welcome to the Pythondex ATM")

pin = int(input('Please enter your four digit pin: '))

if pin == user['pin']:
    while is_quit == False:
        print("what do you want to do")
        print(" Enter 1 to Widthdraw Cash \n Enter 2 for Balance Enquiry \n Enter 3 to Quit")

        query = int(input("Enter the number corresponding to the activity you want to do: "))

        if query == 1:
            widthdraw_cash()
        elif query == 2:
            balance_enquiry()
        elif query == 3:
            is_quit = True

        else:
            print("Please enter a correct value shown")
else:
    print("Entered wrong pin")


Welcome to the Pythondex ATM


Please enter your four digit pin:  1234


what do you want to do
 Enter 1 to Widthdraw Cash 
 Enter 2 for Balance Enquiry 
 Enter 3 to Quit


Enter the number corresponding to the activity you want to do:  1
Enter the amount of money you want to widthdraw:  800


800 Dollars successfully widthdrawn your remaining balance is 200 Dollars

what do you want to do
 Enter 1 to Widthdraw Cash 
 Enter 2 for Balance Enquiry 
 Enter 3 to Quit


Enter the number corresponding to the activity you want to do:  3


In [22]:
# 16. Build a program that checks if a given string is a palindrome or not.

def isPalindrome(s):
    return s == s[::-1]
s = "prajakta"
ans = isPalindrome(s)
 
if ans:
    print("Yes")
else:
    print("No")

No


In [24]:
# 17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.


l1 = [15, 9, 55, 41, 35, 20, 62, 49] 
l1.sort()
trimmed = l1[1:-1]
print(trimmed)
def Average(trimmed): 
    return sum(trimmed) / len(trimmed) 
average = Average(trimmed) 
print("Average of the list =", round(average, 2)) 

[15, 20, 35, 41, 49, 55]
Average of the list = 35.83


In [26]:
# 18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

def convertTemp(c): 
    f = (c * 1.8) + 32
    return f
cel = 37
fahr = convertTemp(cel)
print('%0.1f degrees Celsius is equivalent to %0.1f degrees Fahrenheit' %(cel, fahr))

37.0 degrees Celsius is equivalent to 98.6 degrees Fahrenheit


In [29]:
# 19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

def add(num1, num2):
    return num1 + num2
def subtract(num1, num2):
    return num1 - num2
def multiply(num1, num2):
    return num1 * num2
def divide(num1, num2):
    return num1 / num2
print("Please select operation -\n" \
        "1. Add\n" \
        "2. Subtract\n" \
        "3. Multiply\n" \
        "4. Divide\n")
select = int(input("Select operations form 1, 2, 3, 4 :"))
number_1 = int(input("Enter first number: "))
number_2 = int(input("Enter second number: "))
 
if select == 1:
    print(number_1, "+", number_2, "=", add(number_1, number_2))
elif select == 2:
    print(number_1, "-", number_2, "=", subtract(number_1, number_2))
elif select == 3:
    print(number_1, "*", number_2, "=", multiply(number_1, number_2))
elif select == 4:
    print(number_1, "/", number_2, "=", divide(number_1, number_2))
else:
    print("Invalid input")

Please select operation -
1. Add
2. Subtract
3. Multiply
4. Divide



Select operations form 1, 2, 3, 4 : 3
Enter first number:  4
Enter second number:  5


4 * 5 = 20


In [31]:
# 20. Write a program that determines the roots of a cubic equation using the Cardano formula.

a =  1.0
b =  0.0
c =  0.2 - 1.0
d = -0.7 * 0.2

q = (3*a*c - b**2) / (9 * a**2)
r = (9*a*b*c - 27*a**2*d - 2*b**3) / (54*a**3)

print("q = ", q)
print("r = ", r)

delta = q**3 + r**2

print("delta = ", delta)

rho = (-q**3)**0.5

s_real = rho**(1./3.)
t_real = rho**(1./3.)

print("s [real] = ", s_real)
print("t [real] = ", t_real)

x1 = s_real + t_real - b / (3. * a)

print("x1 = ", x1)

print("should be zero: ", a*x1**3+b*x1**2+c*x1+d)

q =  -0.2666666666666667
r =  0.06999999999999999
delta =  -0.014062962962962975
s [real] =  0.5163977794943223
t [real] =  0.5163977794943223
x1 =  1.0327955589886446
should be zero:  0.13541214906363888


In [ ]:
# Advanced Level:

In [33]:
# 21. Create a program that calculates the income tax based on the user's income and tax brackets.

def calculate(amount, percent): 
    return (amount * percent) / 100
  
def calculate_income_tax(total_income:  
                         float) -> float: 
  
    if total_income <= 250000: 
        return 0
    elif total_income <= 500000: 
        return calculate(total_income - 
                         250000, 5) 
    elif total_income <= 750000: 
        return calculate(total_income - 
                         500000, 10) + 12500
    elif total_income <= 1000000: 
        return calculate(total_income - 
                         750000, 15) + 37500
    elif total_income <= 1250000: 
        return calculate(total_income - 
                         1000000, 20) + 75000
    elif total_income <= 1500000: 
        return calculate(total_income - 
                         1250000, 25) + 125000
    else: 
        return calculate(total_income - 
                         1500000, 30) + 187500
  
  
if __name__ == '__main__': 
    total_income = float(input("What's your \  annual income?\n>>> ")) 
    tax = calculate_income_tax(total_income) 
    print(f"Total tax applicable at \  ₹{total_income} is ₹{tax}") 

What's your \  annual income?
>>>  900000


Total tax applicable at \  ₹900000.0 is ₹60000.0


In [8]:
# 22. Write a program that simulates a rock-paper-scissors game against the computer.

import random
user_action = input("enter your choice from rock, paper and scissors")
possible_actions = ["rock", "paper", "scissors"]
computer_action = random.choice(possible_actions)
print(f"\nYou chose {user_action}, computer chose {computer_action}.\n")


if user_action == computer_action:
    print(f"Both players selected {user_action}. It's a tie!")
elif user_action == "rock":
    if computer_action == "scissors":
        print("Rock smashes scissors! You win!")
    else:
        print("Paper covers rock! You lose.")
elif user_action == "paper":
    if computer_action == "rock":
        print("Paper covers rock! You win!")
    else:
        print("Scissors cuts paper! You lose.")
elif user_action == "scissors":
    if computer_action == "paper":
        print("Scissors cuts paper! You win!")
    else:
        print("Rock smashes scissors! You lose.")

enter your choice from rock, paper and scissors paper



You chose paper, computer chose scissors.

Scissors cuts paper! You lose.


In [19]:
# 23. Develop a program that generates a random password based on user preferences (length, complexity).

import string
import random
characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")
def generate_random_password():
	length = int(input("Enter password length: "))
	random.shuffle(characters)
	password = []
	for i in range(length):
		password.append(random.choice(characters))
	random.shuffle(password)
	print("".join(password))
generate_random_password()

Enter password length:  8


vkYoJ8$&


In [17]:
# 24. Create a program that implements a simple text-based adventure game with branching scenarios.

answer = input("Would you like to play?(yes/no)")

if answer.lower().strip() == "yes":
    answer = input("You reach a cross road, would you like to go right or left?").lower().strip()
    if answer == "left":
        answer = input("You encounter a monster, would you like to run or attack?")
        
        if answer == "attack":
            print("That was not good idea, you lost!")
        else:
            print("Good choice, you made it safely.")
    
    elif answer == "right":
        print("You walk aimlessly to the right and fall on a patch of ice. You injured your leg and can not continue. Game over!")
    
    else:
        print("Invalid choice, you lost!")
else:
    print("That's too bad")

Would you like to play?(yes/no) yes
You reach a cross road, would you like to go right or left? right


You walk aimlessly to the right and fall on a patch of ice. You injured your leg and can not continue. Game over!


In [1]:
# 25. Build a program that solves a linear equation for x, considering different cases.

def solve_linear(equation,var='x'):
    expression = equation.replace("=","-(")+")"
    grouped = eval(expression.replace(var,'1j'))
    return -grouped.real/grouped.imag
solve_linear("x - 2*x + 5*x - 46*(235-24) = x + 2")

3236.0

In [3]:
solve_linear("11*(2*x + 3) = -3*x + 9*(1 + 3*x)")

12.0

In [4]:
# 26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> central processing unit')

# ------1
    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> graphics processing unit')

# -----2
    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> random access memory')

# -----3
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()
    
    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> power supply unit')


# -----4
    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()
    
    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')


# ------5 

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')

Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer


Do you want to play ?  yes

1. what does CPU stand for?  central processing unit


correct! you got 1 point



2. what does GPU stand for?  graphics processing unit


correct! you got 1 point



3. what does RAM stand for?  random access memory


correct! you got 1 point



4. what does PSU stand for?  power supply unit


correct! you got 1 point



5. what does ROM stand for?  read only memory


correct! you got 1 point

number of question is 5
your score is 5
100.0% questions are correct.


In [6]:
# 27. Develop a program that determines whether a given year is a prime number or not.

year = 2015

if year > 1:
    for i in range(2, int(year/2)+1):
        if (year % i) == 0:
            print(year, "year is not a prime number")
            break
    else:
        print(year, "year is a prime number")
else:
    print(year, "year is not a prime number")


2015 year is not a prime number


In [7]:
# 28. Create a program that sorts three numbers in ascending order using conditional statements.

a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))
if a < b:
    if b < c:
        print (a, "<", b, "<", c)
    else:
        if a < c:
            print (a, "<", c, "<", b)
        else:
            print (c, "<", a, "<", b)
else:
    if c < b:
        print (c, "<", b, "<", a)
    else:
        if c < a:
            print (b, "<", c, "<", a)
        else:
            print (b, "<", a, "<", c)

Enter a:  54
Enter b:  12
Enter c:  43


12.0 < 43.0 < 54.0


In [15]:
# 29. Build a program that determines the roots of a quartic equation using numerical methods.

import math 
def equationroots( a, b, c): 
    dis = b * b - 4 * a * c 
    sqrt_val = math.sqrt(abs(dis)) 
    if dis > 0: 
        print("real and different roots") 
        print((-b + sqrt_val)/(2 * a)) 
        print((-b - sqrt_val)/(2 * a))      
    elif dis == 0: 
        print("real and same roots") 
    else:
        print("Complex Roots") 
        print(- b / (2 * a), + i, sqrt_val) 
        print(- b / (2 * a), - i, sqrt_val) 
a = 5
b = 15
c = -24
if a == 0: 
        print("Input correct quadratic equation") 
else:
    equationroots(a, b, c)

real and different roots
1.1551836094703507
-4.155183609470351


In [18]:
# 30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based
# on the user's input.

height = float(input("Enter your height in cm: "))
weight = float(input("Enter your weight in kg: "))
BMI = weight / (height/100)**2
print(f"You BMI is {BMI}")

if BMI <= 18.4:
    print("You are underweight.")
elif BMI <= 24.9:
    print("You are healthy.")
elif BMI <= 29.9:
    print("You are over weight.")
elif BMI <= 34.9:
    print("You are severely over weight.")
elif BMI <= 39.9:
    print("You are obese.")
else:
    print("You are severely obese.")

Enter your height in cm:  155
Enter your weight in kg:  49


You BMI is 20.39542143600416
You are healthy.


In [ ]:
# Challenge Level:

In [19]:
# 31. Create a program that validates a password based on complexity rules (length, characters, etc.).

import string
import random
characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")
def generate_random_password():
	length = int(input("Enter password length: "))
	random.shuffle(characters)
	password = []
	for i in range(length):
		password.append(random.choice(characters))
	random.shuffle(password)
	print("".join(password))
generate_random_password()

Enter password length:  10


ErudCehO2a


In [24]:
# 32. Develop a program that performs matrix addition and subtraction based on user input.

import numpy

A=[ [1, 2, 3], [3, 4, 5], [6, 7, 8] ]

B=[ [5, 6, 7], [1, 2, 3], [5, 3, 8] ]

print("Result: ")
print("Addition:", 
      numpy.add(A,B))
print("Subtraction:", 
      numpy.subtract(A,B))

Result: 
Addition: [[ 6  8 10]
 [ 4  6  8]
 [11 10 16]]
Subtraction: [[-4 -4 -4]
 [ 2  2  2]
 [ 1  4  0]]


In [25]:
# 33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean
# algorithm.

def gcd(m,n):
    if m< n:
        (m,n) = (n,m)
    if(m%n) == 0:
        return n
    else:
        return (gcd(n, m % n))
print(gcd(8,12))

4


In [29]:
# 34. Build a program that performs matrix multiplication using nested loops and conditional statements.

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [3]:
# 35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

import numpy as np
import random
from time import sleep
 
# Creates an empty board
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
 
# Check for empty places on board
def possibilities(board):
    l = []
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
 
# Select a random place for the player
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
 
# Checks whether the player has three
# of their marks in a horizontal row
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a vertical row
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
 
# Checks whether the player has three
# of their marks in a diagonal row 
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
 
# Evaluates whether there is
# a winner or a tie
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
 
# Main function to start the game
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 1]
 [0 0 0]]
Board after 2 move
[[0 0 0]
 [0 0 1]
 [2 0 0]]
Board after 3 move
[[0 0 1]
 [0 0 1]
 [2 0 0]]
Board after 4 move
[[0 0 1]
 [0 0 1]
 [2 2 0]]
Board after 5 move
[[1 0 1]
 [0 0 1]
 [2 2 0]]
Board after 6 move
[[1 0 1]
 [0 2 1]
 [2 2 0]]
Board after 7 move
[[1 0 1]
 [0 2 1]
 [2 2 1]]
Winner is: 1


In [5]:
# 36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

num = 10
n1, n2 = 0, 1
print("Fibonacci Series:", n1, n2, end=" ")
for i in range(2, num):
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    print(n3, end=" ")

print()

Fibonacci Series: 0 1 1 2 3 5 8 13 21 34 


In [7]:
# 37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

def fibonacci(n):
    a,b = 0,1
    for i in range(n):
        a,b = b,a+b
    return a

print("nth term of Fibonacci sequence:", fibonacci(8))

nth term of Fibonacci sequence: 21


In [9]:
# 38. Create a program that generates a calendar for a given month and year using conditional statements.

mm = 7
yy = 2022
  
month ={1:'January', 2:'February', 3:'March',  
        4:'April', 5:'May', 6:'June', 7:'July', 
        8:'August', 9:'September', 10:'October', 
        11:'November', 12:'December'} 
   
# code below for calculation of odd days 
day =(yy-1)% 400
day = (day//100)*5 + ((day % 100) - (day % 100)//4) + ((day % 100)//4)*2
day = day % 7
  
nly =[31, 28, 31, 30, 31, 30,  
      31, 31, 30, 31, 30, 31] 
ly =[31, 29, 31, 30, 31, 30,  
     31, 31, 30, 31, 30, 31] 
s = 0
  
if yy % 4 == 0: 
    for i in range(mm-1): 
        s+= ly[i] 
else: 
    for i in range(mm-1): 
        s+= nly[i] 
    day += s % 7
    day = day % 7
    
# variable used for white space filling  
# where date not present 
space ='' 
space = space.rjust(2, ' ') 
  
# code below is to print the calendar 
print(month[mm], yy) 
print('Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa') 
  
if mm == 9 or mm == 4 or mm == 6 or mm == 11:  
    for i in range(31 + day): 
          
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print() 
elif mm == 2: 
    if yy % 4 == 0: 
        p = 30
    else: 
        p = 29
          
    for i in range(p + day): 
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print()  
else: 
    for i in range(32 + day): 
          
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print() 

July 2022
Su Mo Tu We Th Fr Sa
               01 02 
03 04 05 06 07 08 09 
10 11 12 13 14 15 16 
17 18 19 20 21 22 23 
24 25 26 27 28 29 30 
31 

In [10]:
# 39. Build a program that simulates a basic text-based blackjack game against the computer.

import random 

card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades'] 
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'] 
deck = [(card, category) for category in card_categories for card in cards_list] 

def card_value(card): 
	if card[0] in ['Jack', 'Queen', 'King']: 
		return 10
	elif card[0] == 'Ace': 
		return 11
	else: 
		return int(card[0]) 

random.shuffle(deck) 
player_card = [deck.pop(), deck.pop()] 
dealer_card = [deck.pop(), deck.pop()] 

while True: 
	player_score = sum(card_value(card) for card in player_card) 
	dealer_score = sum(card_value(card) for card in dealer_card) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("\n") 
	choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower() 
	if choice == "play": 
		new_card = deck.pop() 
		player_card.append(new_card) 
	elif choice == "stop": 
		break
	else: 
		print("Invalid choice. Please try again.") 
		continue

	if player_score > 21: 
		print("Cards Dealer Has:", dealer_card) 
		print("Score Of The Dealer:", dealer_score) 
		print("Cards Player Has:", player_card) 
		print("Score Of The Player:", player_score) 
		print("Dealer wins (Player Loss Because Player Score is exceeding 21)") 
		break

while dealer_score < 17: 
	new_card = deck.pop() 
	dealer_card.append(new_card) 
	dealer_score += card_value(new_card) 

print("Cards Dealer Has:", dealer_card) 
print("Score Of The Dealer:", dealer_score) 
print("\n") 

if dealer_score > 21: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)") 
elif player_score > dealer_score: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Player wins (Player Has High Score than Dealer)") 
elif dealer_score > player_score: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("Dealer wins (Dealer Has High Score than Player)") 
else: 
	print("Cards Dealer Has:", dealer_card) 
	print("Score Of The Dealer:", dealer_score) 
	print("Cards Player Has:", player_card) 
	print("Score Of The Player:", player_score) 
	print("It's a tie.")

Cards Player Has: [('Jack', 'Diamonds'), ('9', 'Diamonds')]
Score Of The Player: 19




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('Jack', 'Diamonds'), ('9', 'Diamonds'), ('7', 'Diamonds')]
Score Of The Player: 26




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Dealer Has: [('3', 'Diamonds'), ('Queen', 'Diamonds')]
Score Of The Dealer: 13
Cards Player Has: [('Jack', 'Diamonds'), ('9', 'Diamonds'), ('7', 'Diamonds'), ('Jack', 'Clubs')]
Score Of The Player: 26
Dealer wins (Player Loss Because Player Score is exceeding 21)
Cards Dealer Has: [('3', 'Diamonds'), ('Queen', 'Diamonds'), ('10', 'Spades')]
Score Of The Dealer: 23


Cards Dealer Has: [('3', 'Diamonds'), ('Queen', 'Diamonds'), ('10', 'Spades')]
Score Of The Dealer: 23
Cards Player Has: [('Jack', 'Diamonds'), ('9', 'Diamonds'), ('7', 'Diamonds'), ('Jack', 'Clubs')]
Score Of The Player: 26
Player wins (Dealer Loss Because Dealer Score is exceeding 21)


In [12]:
# 40. Write a program that generates the prime factors of a given number using trial division.

def primeFactors(n):
    spf = [0 for i in range(n+1)]
    spf[1] = 1
    for i in range(2, n+1):
        spf[i] = i
    for i in range(4, n+1, 2):
        spf[i] = 2
  
    for i in range(3, int(n**0.5)+1):
        if spf[i] == i:
            for j in range(i*i, n+1, i):
                if spf[j] == j:
                    spf[j] = i
                      
    while n != 1:
        print(spf[n], end=" ")
        n = n // spf[n]

n = 4218
primeFactors(n)

2 3 19 37 